Django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from app01 import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.article_list, name='index'),

    path('article/', include('app01.urls', namespace='article')),

    path('userprofile/', include('userprofile.urls', namespace='userprofile')),

    path('comment/', include('comment.urls', namespace='comment')),

    path('password-reset/', include('password_reset.urls')),

    path('accounts/', include('allauth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app01/urls.py
from django.urls import path
from app01 import tests
from app01 import views

app_name = 'app01'

urlpatterns = [
    path('test/', tests.test),
    path('article_list/', views.article_list, name='article_list'),

    # 这里需要传递名叫id的整数到视图函数中去。

    path('article_detail/<int:id>/', views.article_detail, name='article_detail'),
    path('article_create/', views.article_create, name='article_create'),
    path('article_delete/<int:id>/', views.article_delete, name='article_delete'),
    path('article_update/<int:id>/', views.article_update, name='article_update'),



]

userprofile/urls.py
from django.urls import path
from userprofile import views

app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
    path('edit/<int:id>/', views.profile_edit, name='edit'),


]

templates/back_to_top_func.html
<!-- 参考了 鹦鹉 的代码，在此致谢 -->
<!-- https://ezbox.idv.tw/131/back-to-top-button-without-images -->

<button type="button" id="BackTop" class="toTop-arrow" style="z-index: 100;"></button>

<script>
    // 向上滚动的函数
    $(function () {
        $('#BackTop').click(function () {
            $('html,body').animate({scrollTop: 0}, 500);
        });
        $(window).scroll(function () {
            if ($(this).scrollTop() > 300) {
                $('#BackTop').fadeIn(300);
            } else {
                $('#BackTop').stop().fadeOut(300);
            }
        }).scroll();
    });
</script>

<style>
    /* 按钮边框的大小、位置、样式 */
    .toTop-arrow {
        width: 3rem;
        height: 3rem;
        padding: 0;
        margin: 0;
        border: 0;
        border-radius: 33%;
        opacity: 0.7;
        background: black;
        cursor: pointer;
        position: fixed;
        right: 1.5rem;
        bottom: 1.5rem;
        display: none;
    }

    /* 绘制按钮中的向上箭头 */
    .toTop-arrow::before, .toTop-arrow::after {
        width: 26px;
        height: 6px;
        border-radius: 2px;
        background: #ff693b;
        position: absolute;
        content: "";
    }

    .toTop-arrow::before {
        transform: rotate(-45deg) translate(0, -50%);
        left: 0.4rem;
    }

    .toTop-arrow::after {
        transform: rotate(45deg) translate(0, -50%);
        right: 0.4rem;
    }

    /* 取消点击按钮时的聚焦 */
    .toTop-arrow:focus {
        outline: none;
    }
</style>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <!-- 预留网站标题的位置 -->
    <title>{% block title %}{% endblock %}</title>
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">
    <!-- 引入fontawesome的css文件 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.14.0/css/all.min.css">

</head>

<body>
    <!-- 引入导航栏 -->
    {% include 'header.html' %}
     <!-- 新增两个 div 容器 -->
    <div id="wrapper">
    <!-- 预留具体页面的位置 -->
    {% block content %}{% endblock content %}
        <div id="push"></div>
    </div>
    <!-- 引入注脚 -->
    {% include 'footer.html' %}
    <!-- bootstrap.js 依赖 jquery.js 和popper.js，因此在这里引入 -->
    <script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.3.0/jquery.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1-lts/dist/umd/popper.min.js"></script>

    <!-- 引入bootstrap的js文件 -->
    <script src="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.js"></script>

    <script src="{% static 'layer/layer.js' %}"></script>

    <!-- 预留JS的位置 -->
    {% block script %}{% endblock script %}
    <!--向上滚动按钮->
    {% include 'back_to_top_func.html' %}

<!-- 增加样式 -->
<style>
    html, body {
        height: 100%;
        margin: 0;
    }
    #wrapper {
        min-height: 100%;
        margin-bottom: -60px;
    }
    #footer,
    #push {
        height: 60px;
    }
</style>

</body>

</html>

templates/footer.html
{% load static %}
<!-- Footer -->
<div>
    <br><br><br>
</div>
<footer class="py-3 bg-dark" id="footer">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Yasina_20 2021</p>
    </div>
</footer>

templates/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
    <!-- 导航栏商标 -->
    <a class="navbar-brand" href="#">
        <i class="fas fa-home"></i>
        哲学之家
    </a>
    <!-- 导航入口 -->
    <div>
      <ul class="navbar-nav">
        <!-- 条目 -->
        <li class="nav-item">
           <a class="nav-link" href="{% url 'app01:article_list' %}">全部文章</a>
        </li>
        {% if user.is_authenticated %}
            <!-- 如果用户已经登录，则显示用户名下拉框 -->
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{ user.username }}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'app01:article_create' %}">写文章</a>
                <a class="dropdown-item" href='{% url "userprofile:edit" user.id %}'>个人信息</a>
                <a class="dropdown-item" href="#" onclick="user_delete()">删除用户</a>
                <a class="dropdown-item" href="{% url 'userprofile:logout' %}">退出登录</a>
            </div>
        </li>
            <!-- 如果用户未登录，则显示 “登录” -->
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="/accounts/login/">登录</a>
        </li>
        {% endif %}
      </ul>
    </div>

  </div>
</nav>

{% if user.is_authenticated %}
<form
    style="display:none;"
    id="user_delete"
    action="{% url 'userprofile:delete' user.id %}"
    method="POST"
>
{% csrf_token %}
    <button type="submit">发送</button>
</form>
    <script>
        function user_delete() {
            // 调用layer弹窗组件
            layer.open({
                title: "确认删除",
                content: "确认删除用户资料吗？",
                yes: function(index, layero) {
                    $('form#user_delete button').click();
                    layer.close(index);
                },
            })
        }
    </script>
{% endif %}