Django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from app01 import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.article_list, name='index'),

    path('article/', include('app01.urls', namespace='article')),

    path('userprofile/', include('userprofile.urls', namespace='userprofile')),

    path('comment/', include('comment.urls', namespace='comment')),

    path('password-reset/', include('password_reset.urls')),

    path('accounts/', include('allauth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app01/urls.py
from django.urls import path
from app01 import tests
from app01 import views

app_name = 'app01'

urlpatterns = [
    path('test/', tests.test),
    path('article_list/', views.article_list, name='article_list'),

    # 这里需要传递名叫id的整数到视图函数中去。

    path('article_detail/<int:id>/', views.article_detail, name='article_detail'),
    path('article_create/', views.article_create, name='article_create'),
    path('article_delete/<int:id>/', views.article_delete, name='article_delete'),
    path('article_update/<int:id>/', views.article_update, name='article_update'),



]

comment/urls.py
from django.urls import path
from comment import views

app_name = 'comment'


urlpatterns = [
    path('post_comment/<int:article_id>/', views.post_comment, name='post_comment'),

]

userprofile/urls.py
from django.urls import path
from userprofile import views

app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
    path('edit/<int:id>/', views.profile_edit, name='edit'),


]

templates/article/create.html
{% extends "base.html" %} {% load static %}

{% block title %} 写文章 {% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 写文章表单 -->
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <!-- 提交文章的表单 -->
            <form method="post" action="." enctype="multipart/form-data">
                <!-- Django中需要POST数据的地方都必须有csrf_token -->
                {% csrf_token %}
                <!-- 文章标题 -->
                <div class="form-group">
                    <!-- 标题 -->
                    <label for="title">文章标题</label>
                    <input type="text" class="form-control" id="title" name="title">
                </div>
                <!-- 标题图 -->
                <div class="form-group">
                    <label for="avatar">标题图</label>
                    <input type="file" class="form-control-file" name="avatar" id="avatar">
                </div>
                <!-- 文章栏目 -->
                <div class="form-group">
                    <label for="column">栏目</label>
                    <select class="form-control" id="column" name="column">
                            <option value="none">无</option>
                        {% for column in columns %}
                            <option value="{{ column.id }}">{{ column }}</option>
                        {% endfor %}
                    </select>

                <!-- 标签 -->
                <label for="tags">标签</label>
                <input type="text"
                        class="form-control col-3"
                        id="tags"
                        name="tags">
                </div>
                <!-- 文章正文 -->
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本区域 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/article/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}文章详情{% endblock title %}


{% block content %}
<script src="{% static 'ckeditor/ckeditor/plugins/prism/lib/prism/prism_patched.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'prism/prism.css' %}">
<div class="container">
    <div class="row">
        <!-- 文章内容 -->
        <div class="col-9">
            <!-- 标题及作者 -->
            <h1 class="mt-4 mb-4">{{ article.title }}</h1>
            <div class="alert alert-success">
                作者：{{ article.author }} ·
                浏览：{{ article.total_views }}

                {% if user == article.author %}
                    · <a href="#" onclick="confirm_delete()">删除文章</a>
                    · <a href="{% url "app01:article_update" article.id %}">
                        编辑文章
                    </a>
                {% endif %}
            </div>
            <!-- 内容 -->
            <div><p>{{ article.body|safe }}</p></div>
            <div class="alert alert-success">
                发布：{{ article.created|date:'Y-m-d' }} ·
                更新：{{ article.updated|date:'Y-m-d' }}
            </div>
            <!-- 发表评论 -->
            <hr>
            {% if user.is_authenticated %}
                <div>
                    <form action="{% url 'comment:post_comment' article.id %}" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="body">
                                <strong class="btn btn-success" onclick="fayan()">
                                    我也要发言
                                </strong>
                            </label>
                            <div id="pinglunkuang" style="display: none">
                                {{ comments_form.media }}
                                {{ comments_form.body }}
                                <!-- 提交按钮 -->
                                <button type="submit" class="btn btn-primary ">发送</button>
                            </div>
                        </div>
                    </form>
                </div>
                <br>
            {% else %}
                <br>
                <h5 class="row justify-content-center">
                    请<a href="{% url 'userprofile:login' %}">登录</a>后回复
                </h5>
                <br>
            {% endif %}
                <!-- 显示评论 -->
            <h4>共有{{ comments.count }}条评论</h4>
            <div>
                {% for comment in comments %}
                    <hr>
                    <p>
                        <strong style="color: pink">
                            {{ comment.user }}
                        </strong> 于
                        <span style="color: green">
                            {{ comment.created|date:"Y-m-d H:i:s" }}
                        </span> 时说：
                    </p>
                    <pre style="font-family: inherit; font-size: 1em;">
        {{ comment.body|safe }}</pre>
                {% endfor %}
            </div>
        </div>
        <!-- 新增的目录 toc是一串html，有目录以a标签呈现-->
        {% if 'href' in toc %}
        <div class="col-3 mt-4">
            <h6><p></p><strong>目录</strong></h6>
            <hr>
            <div>
                {{ toc|safe }}
            </div>
        </div>
        {% endif %}
    </div>
</div>

<!-- 新增一个隐藏的表单 -->
<form
      style="display:none;"
      id="safe_delete"
      action="{% url 'app01:article_delete' article.id %}"
      method="POST"
      >
    {% csrf_token %}
    <button type="submit">发送</button>
</form>


{% endblock content %}

{% block script %}
<script>
    // 删除文章的函数
    function confirm_delete() {
        // 调用layer弹窗组件
        layer.open({
            // 弹窗标题
            title: "确认删除",
            // 正文
            content: "确认删除这篇文章吗？",
            // 点击确定按钮后调用的回调函数
            yes: function(index, layero) {
                $('form#safe_delete button').click();
                layer.close(index);
            },
        })
    }
    function fayan(){
        $('#pinglunkuang').css('display','block');
    }
    $(".django-ckeditor-widget").removeAttr('style');
</script>
{% endblock script %}

templates/article/list.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load static %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    首页
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 定义放置文章标题的div容器 -->
<div class="container">
    <!-- 排序 -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
            <a href="{% url 'app01:article_list' %}?search={{ search }}">
                最新</a>
            </li>
             <li class="breadcrumb-item">
            <a href="{% url 'app01:article_list' %}?order=total_views&search={{ search }}">
                最热</a>
             </li>
        </ol>
    </nav>
    <!-- 搜索栏 -->
    <div class="row">
        <div class="col-auto mr-auto">
            <form class="form-inline" >
                <label class="sr-only">content</label>
                <input type="text"
                    class="form-control mb-2 mr-sm-2"
                    name="search"
                    placeholder="搜索文章..."
                >
                <input type="submit" value="搜索" class="btn btn-primary">
            </form>
        </div>
    </div>
    <!-- 搜索提示语 -->
    {% if search %}
        {% if articles %}
            <h4><span style="color: red">"{{ search }}"</span>的搜索结果如下：</h4>
            <hr>
        {% else %}
            <h4>暂无<span style="color: red">"{{ search }}"</span>有关的文章。</h4>
            <hr>
        {% endif %}
    {% endif %}
    <!-- 目标文章列表--修改循环加入标题图 -->
    <div class="row mt-2">
        {% for article in articles %}
        <!-- 文章内容 -->
            <!--如果有标题图则加入-->
            {% if article.avatar %}
                <div class="col-3">
                    <img src="{{ article.avatar.url }}" alt="avatar" style="max-width:100%; border-radius: 20px">
                </div>
                <div class="col-9">
            {% else %}
                <div class="col-12">
            {% endif %}
                <!-- 栏目 -->
                {% if article.column %}
                    <button type="button"
                        class="btn btn-sm mb-2
                            {% if article.column.title == 'Python' %}
                                btn-success
                            {% elif article.column.title == 'JAVA' %}
                                btn-primary
                            {% elif article.column.title == 'HTML' %}
                                btn-info
                            {% endif %}
                        ">
                        {{ article.column }}
                    </button>
                {% endif %}
                <!-- 标签 -->
                <span>
                    {% for tag in article.tags.all %}
                    <a href="{% url 'article:article_list' %}?tags={{ tag }}" class="badge badge-secondary">{{ tag }}</a>
                    {% endfor %}
                </span>
                <!-- 标题 -->
                <h4>
                    <b>
                        <a href="{% url 'article:article_detail' article.id %}" style="color: black;">
                            {{ article.title }}</a>
                    </b>
                </h4>
                <!-- 摘要 -->
                <p style="color: gray;">
                    {{ article.body|slice:'100' }}...
                </p>
                <!-- 注脚信息 -->
                <p>
                    <span style="color: green;">
                        {{ article.total_views }} 浏览&nbsp;&nbsp;&nbsp;
                    </span>
                    <span style="color: blue;">
                        {{ article.created|date:'Y-m-d' }} 发布&nbsp;&nbsp;&nbsp;
                    </span>
                    <span style="color: darkred;">
                        {{ article.updated|date:'Y-m-d' }} 更新
                    </span>
                </p><hr style="width: 100%;"/>
            </div>
        {% endfor %}

    </div>
    <!-- 页码导航 -->
    <div class="pagination row">
        <div class="m-auto">
            <span class="step-links">
                <!-- 如果不是第一页，则显示上翻按钮 -->
                {% if articles.has_previous %}
                    <a href="?page=1&order={{ order }}&search={{ search }}&tag={{ tag }}" class="btn btn-success">
                        &laquo; 1
                    </a>
                    <span>...</span>
                    <a href="?page={{ articles.previous_page_number }}&order={{ order }}&search={{ search }}&tag={{ tag }}" class="btn btn-secondary">
                        {{ articles.previous_page_number }}
                    </a>
                {% endif %}

                <!-- 当前页面 -->
                <span class="current btn btn-danger btn-lg">
                    {{ articles.number }}
                </span>

                <!-- 如果不是最末页，则显示下翻按钮 -->
                {% if articles.has_next %}
                    <a href="?page={{ articles.next_page_number }}&order={{ order }}&search={{ search }}&tag={{ tag }}" class="btn btn-secondary">
                        {{ articles.next_page_number }}
                    </a>
                    <span>...</span>
                    <a href="?page={{ articles.paginator.num_pages }}&order={{ order }}&search={{ search }}&tag={{ tag }}" class="btn btn-success">
                        {{ articles.paginator.num_pages }} &raquo;
                    </a>
                {% endif %}
            </span>
        </div>
    </div>
</div>

{% endblock content %}

templates/article/update.html
{% extends "base.html" %} {% load static %}
{% block title %} 更新文章 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">文章标题</label>
                    <!-- 在 value 属性中指定文本框的初始值为旧的内容，即 article 对象中的 title 字段 -->
                    <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
                </div>
                <div class="form-group">
                    <label for="column">栏目</label>
                    <select class="form-control" id="column" name="column">
                        <option value="none">请选择栏目..</option>
                        {% for column in columns %}
                        <option value="{{ column.id }}"{% if column.id == article.column.id %} selected {% endif %}>
                            {{ column }}
                        </option>
                        {% endfor %}
                    </select>
                </div>
                <!-- 文章正文 -->
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本域不需要 value 属性，直接在标签体中嵌入数据即可 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12">{{ article.body }}</textarea>
                </div>
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}